.deploy: &deploy
  tags: [docker]
  image: alpine:latest
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$ARQ_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  stage: deploy
  when: manual


stages:
  - build_package
  - deploy

build_package:
  tags: [docker]
  stage: build_package
  image: docker:18
  before_script:
    - docker info
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

  when: manual

deploy_tst:
  <<: *deploy
  script:
    - ssh -o "StrictHostKeyChecking=no" -p 22 root@91.121.185.31 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh -o "StrictHostKeyChecking=no" -p 22 root@91.121.185.31 "echo $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - ssh -o "StrictHostKeyChecking=no" -p 22 root@91.121.185.31 "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - ssh -o "StrictHostKeyChecking=no" -p 22 root@91.121.185.31 "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest"
    - ssh -o "StrictHostKeyChecking=no" -p 22 root@91.121.185.31 "cd /root/capacitacion/fastapi_microservice && docker-compose up --build -d"

  when: manual

